import {listIncomeReferences,createIncomeDraft,previewIncomeAdoption} from './income-preview.mjs';
import {loadIncomeState,applyIncomePreview,undoIncomeApply,incomeUndoStatus} from './income-workflow.mjs';
import {cashflowSourceSignature as signature} from './cashflow-sources.mjs';
import {migrateConfig} from './storage.mjs';
const normalized=s=>({config:migrateConfig(s.config),scenarios:s.scenarios.map(x=>({...x,config:migrateConfig(x.config)}))});
export function assertIncomeScreenMatches(raw,displayed){if(signature(normalized(raw))!==signature(normalized(displayed)))throw new Error('保存内容と表示中の設定が異なります。再読み込みしてください。');}
const money=n=>`${Number(n).toLocaleString('ja-JP',{maximumFractionDigits:3})}万円`;
const period=r=>`${r.period.fromAge}～${r.period.toAge}歳`;
const unit=r=>r.unit==='monthly'?'月額':'年額';
export function mountIncomeSheet({getState,onCommit,showNotice,storage=localStorage,doc=document}){
 const el=id=>doc.getElementById('income'+id);let base=null,refs=[],preview=null,busy=false,blocked=false;
 const error=s=>{el('Error').textContent=s;el('Error').hidden=!s;};
 function invalidate(){preview=null;el('Preview').hidden=true;el('Reviewed').checked=false;}
 function buttons(){for(const id of ['Rule','Amount','Treatment'])el(id).disabled=busy||blocked;el('Trial').disabled=busy||blocked||!refs.length;el('Apply').disabled=busy||blocked||!preview?.changed||!el('Reviewed').checked;el('Undo').disabled=busy||blocked||!base||!incomeUndoStatus(base).available;}
 function selected(){return refs[Number(el('Rule').value)];}
 function selection(){invalidate();const r=selected();el('Amount').value=r?String(r.amount):'';el('Adopted').textContent=r?`参考値：${money(r.amount)}／${unit(r)}・${period(r)}\n内部ID：${r.itemId}\n出典：${r.sourceRefs.map(x=>x.path).join(', ')}\n価格基準：名目固定`:'採用できる参考追加収入がありません。';el('State').textContent='未試算';buttons();}
 function rebuild(){refs=listIncomeReferences(base);el('Rule').replaceChildren();refs.forEach((r,i)=>{const o=doc.createElement('option');o.value=String(i);o.textContent=`${r.label}｜${period(r)}｜${unit(r)}`;el('Rule').append(o);});el('Rule').value=refs.length?'0':'';selection();}
 function render(){if(!getState().config)return;try{const current=loadIncomeState(storage);assertIncomeScreenMatches(current,getState());if(!base){base=current;rebuild();}else if(signature(base)!==signature(current)){blocked=true;invalidate();error('別の操作で設定が更新されました。入力は残しています。再読み込みして再試算してください。');}const w=current.config.incomeWorkflow;el('History').textContent=w?.lastApply?`反映日時：${new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',dateStyle:'short',timeStyle:'medium'}).format(new Date(w.lastApply.at))} 日本時間`:'取消できる直前反映はありません。';}catch(e){blocked=true;invalidate();error(e.message);}buttons();}
 el('Rule').addEventListener('change',()=>{if(!busy&&!blocked){error('');selection();}});
 for(const id of ['Amount','Treatment'])el(id).addEventListener(id==='Amount'?'input':'change',()=>{invalidate();el('State').textContent='未反映の入力あり';buttons();});
 el('Reviewed').addEventListener('change',buttons);
 el('Trial').addEventListener('click',()=>{if(busy||blocked)return;invalidate();error('');try{const current=loadIncomeState(storage);assertIncomeScreenMatches(current,getState());if(signature(current)!==signature(base))throw new Error('保存内容が更新されています。再読み込みしてください。');const r=selected(),text=el('Amount').value.trim();if(!r||!text||!Number.isFinite(Number(text))||Number(text)<0)throw new Error('0以上の金額を入力してください。');const d=createIncomeDraft(base);d.selection={itemId:r.itemId,ruleRef:r.ruleRef,period:r.period,unit:r.unit,priceBasis:r.priceBasis,amount:Number(text),fundingTreatment:el('Treatment').value};preview=previewIncomeAdoption(base,d);el('PreviewBody').textContent=[preview.notice,`${money(preview.reference.amount)} → 採用 ${money(Number(text))}／${unit(r)}・${period(r)}`,`計上先：${el('Treatment').value==='separate'?'計画資産へ別枠計上':'給与生活中は家計内振替'}`,`対象月：${preview.months.map(x=>x.month).join('、')||'計上差なし'}`,`年次差額：${preview.annualDeltas.map(x=>`${x.age}歳 ${x.delta>=0?'+':''}${money(x.delta)}`).join('、')||'なし'}`,`最終資産：${money(preview.finalAssetBefore)} → ${money(preview.finalAssetAfter)}`,preview.forecastBefore?`実績反映後の最終資産：${money(preview.forecastBefore.projection.finalAsset)} → ${money(preview.forecastAfter?.projection.finalAsset)}`:'実績なし：再予測比較なし','給与・年金・雇用保険・iDeCo受取・管理予算・支出内訳は変更しません。'].join('\n');el('Preview').hidden=false;el('State').textContent=preview.changed?'試算済み・未反映':'採用値と同じ（保存不要）';}catch(e){error(e.message);}buttons();});
 async function action(undo){if(busy||blocked||(!undo&&(!preview?.changed||!el('Reviewed').checked)))return;busy=true;buttons();error('');let saved;try{assertIncomeScreenMatches(loadIncomeState(storage),getState());saved=undo?await undoIncomeApply(base,{storage}):await applyIncomePreview(base,preview,{storage});}catch(e){error(`保存できませんでした。入力は保持しています。${e.message}`);busy=false;buttons();return;}base=saved.state;invalidate();rebuild();el('State').textContent=undo?'取消を保存しました':'反映済み';try{onCommit(saved);showNotice(undo?'直前の追加収入反映を取り消しました。':'追加収入を集計表に反映しました。');}catch{blocked=true;error('保存済みですが表示を更新できません。再読み込みしてください。');busy=false;buttons();return;}busy=false;render();}
 el('Apply').addEventListener('click',()=>action(false));el('Undo').addEventListener('click',()=>action(true));
 return {render,invalidate(){blocked=true;invalidate();error('別画面で更新されました。入力を控えてから再読み込みしてください。');buttons();},reset(){base=null;refs=[];blocked=false;invalidate();error('');render();}};
}
