import test from 'node:test';
import assert from 'node:assert/strict';
import {migrateConfig,STATE_KEY} from './storage.mjs';
import {listIncomeReferences,createIncomeDraft,previewIncomeAdoption} from './income-preview.mjs';
import {loadIncomeState,applyIncomePreview,undoIncomeApply,incomeUndoStatus} from './income-workflow.mjs';
class Memory{values=new Map();writes=0;fail=false;onGet=null;getItem(k){if(this.onGet)this.onGet(k);return this.values.get(k)??null;}setItem(k,v){if(this.fail)throw new Error('QuotaExceeded');this.writes++;this.values.set(k,String(v));}removeItem(){throw new Error('old keys must remain');}}
function setup(){const c=migrateConfig({people:{primary:{birthDate:'1980-08-27'},spouse:{birthDate:'1981-05-01'}},plan:{startAge:64,endAge:67,startDate:'2044-08-27',initialAsset:1000,initialAssetIncludesIdeco:false,afterTaxReturn:0,inflation:0},employment:{primary:{mainRetirement:{baseDate:'2045-08-27'},sideWork:{monthlyGross:0}},spouse:{sideWork:{monthlyGross:0}}},income:{pensions:{primary:{annualAtStart:0},spouse:{annualAtStart:0}}},budgets:[{fromAge:65,toAge:90,annualBudget:0}],unemployment:{baselineMode:'none'},events:[]});c.cashflow.manualIncomeItems=[{key:'gift',label:'贈与',unit:'annual',periods:[{fromAge:65,toAge:65,amount:120}]}];const state={config:c,scenarios:[{id:'a',name:'A',role:'scenario',selected:true,config:structuredClone(c)},{id:'b',name:'B',role:'reference',selected:false,config:structuredClone(c)}],future:{keep:1}};const storage=new Memory();storage.setItem(STATE_KEY,JSON.stringify(state));storage.values.set('retirement-sim-config-v0.9','old');return {state,storage};}
function proposal(state,amount=120){const r=listIncomeReferences(state)[0],d=createIncomeDraft(state);d.selection={itemId:r.itemId,ruleRef:r.ruleRef,period:r.period,unit:r.unit,priceBasis:r.priceBasis,amount,fundingTreatment:'separate'};return previewIncomeAdoption(state,d);}
test('apply uses one atomic write and preserves scenarios and unknown envelope',async()=>{const {state,storage}=setup(),writes=storage.writes,n=await applyIncomePreview(state,proposal(state),{storage,now:'2026-09-29T14:00:00Z'});assert.equal(storage.writes,writes+1);assert.equal(n.state.config.cashflow.periodOverrides.length,1);assert.deepEqual(n.state.scenarios,state.scenarios);assert.deepEqual(n.state.future,state.future);assert.equal(incomeUndoStatus(loadIncomeState(storage)).available,true);assert.equal(storage.values.get('retirement-sim-config-v0.9'),'old');});
test('reload and undo remove only the inserted adoption row',async()=>{const {state,storage}=setup();state.config.cashflow.periodOverrides=[{kind:'income',key:'other',fromAge:65,toAge:65,amount:12,unit:'annual',fundingTreatment:'separate',future:1}];storage.setItem(STATE_KEY,JSON.stringify(state));const n=await applyIncomePreview(state,proposal(state),{storage}),u=await undoIncomeApply(loadIncomeState(storage),{storage});assert.deepEqual(u.state.config.cashflow.periodOverrides,state.config.cashflow.periodOverrides);assert.equal(u.state.config.incomeWorkflow.lastApply,null);assert.deepEqual(u.state.scenarios,state.scenarios);});
test('reapply updates one adoption row and undo restores prior adopted value',async()=>{const {state,storage}=setup(),one=await applyIncomePreview(state,proposal(state),{storage}),two=await applyIncomePreview(one.state,proposal(one.state,180),{storage}),u=await undoIncomeApply(two.state,{storage});assert.equal(two.state.config.cashflow.periodOverrides.length,1);assert.equal(two.state.config.cashflow.periodOverrides[0].amount,180);assert.equal(u.state.config.cashflow.periodOverrides[0].amount,120);});
test('retry and concurrent double submit never duplicate rows or history',async()=>{const {state,storage}=setup(),p=proposal(state),one=await applyIncomePreview(state,p,{storage}),writes=storage.writes,retry=await applyIncomePreview(state,p,{storage});assert.equal(retry.alreadyApplied,true);assert.equal(storage.writes,writes);assert.equal(retry.state.config.incomeWorkflow.history.length,1);const second=proposal(one.state,180),all=await Promise.allSettled([applyIncomePreview(one.state,second,{storage}),applyIncomePreview(one.state,second,{storage})]);assert.ok(all.some(x=>x.status==='fulfilled'));assert.equal(loadIncomeState(storage).config.cashflow.periodOverrides.length,1);});
test('save failure keeps current state and reusable proposal',async()=>{const {state,storage}=setup(),p=proposal(state),raw=storage.getItem(STATE_KEY);storage.fail=true;await assert.rejects(applyIncomePreview(state,p,{storage}),/QuotaExceeded/);assert.equal(storage.getItem(STATE_KEY),raw);storage.fail=false;assert.equal((await applyIncomePreview(state,p,{storage})).saved,true);});
test('undo failure keeps adoption and history',async()=>{const {state,storage}=setup(),n=await applyIncomePreview(state,proposal(state),{storage}),raw=storage.getItem(STATE_KEY);storage.fail=true;await assert.rejects(undoIncomeApply(n.state,{storage}),/QuotaExceeded/);assert.equal(storage.getItem(STATE_KEY),raw);assert.equal(incomeUndoStatus(n.state).available,true);});
for(const field of ['config','scenario','actual','envelope'])test(`stale ${field} update blocks apply`,async()=>{const {state,storage}=setup(),p=proposal(state),live=structuredClone(state);if(field==='config')live.config.plan.inflation=1;if(field==='scenario')live.scenarios[0].name='later';if(field==='actual')live.config.actuals={65:{endAsset:1}};if(field==='envelope')live.future.keep=2;storage.setItem(STATE_KEY,JSON.stringify(live));const raw=storage.getItem(STATE_KEY);await assert.rejects(applyIncomePreview(state,p,{storage}),/更新/);assert.equal(storage.getItem(STATE_KEY),raw);});
test('later unrelated edits survive undo',async()=>{const {state,storage}=setup(),n=await applyIncomePreview(state,proposal(state),{storage});n.state.config.actuals={65:{endAsset:1120}};n.state.config.reviews={65:{note:'later'}};n.state.scenarios[0].selected=false;n.state.future.new=1;storage.setItem(STATE_KEY,JSON.stringify(n.state));const u=await undoIncomeApply(n.state,{storage});assert.deepEqual(u.state.config.actuals,n.state.config.actuals);assert.deepEqual(u.state.config.reviews,n.state.config.reviews);assert.equal(u.state.scenarios[0].selected,false);assert.equal(u.state.future.new,1);});
test('later edit or duplicate adoption stops undo',async()=>{for(const mode of ['edit','duplicate']){const {state,storage}=setup(),n=await applyIncomePreview(state,proposal(state),{storage});if(mode==='edit')n.state.config.cashflow.periodOverrides[0].amount=999;else n.state.config.cashflow.periodOverrides.push(structuredClone(n.state.config.cashflow.periodOverrides[0]));storage.setItem(STATE_KEY,JSON.stringify(n.state));assert.equal(incomeUndoStatus(n.state).available,false);await assert.rejects(undoIncomeApply(n.state,{storage}));}});
test('same value after adoption causes no write or new history',async()=>{const {state,storage}=setup(),n=await applyIncomePreview(state,proposal(state),{storage}),p=proposal(n.state),writes=storage.writes,x=await applyIncomePreview(n.state,p,{storage});assert.equal(p.changed,false);assert.equal(x.saved,false);assert.equal(storage.writes,writes);assert.equal(x.state.config.incomeWorkflow.history.length,1);});
test('malformed workflow and corrupt integrated JSON never fall back',async()=>{const {state,storage}=setup();state.config.incomeWorkflow={history:'bad',lastApply:null};storage.setItem(STATE_KEY,JSON.stringify(state));await assert.rejects(applyIncomePreview(state,proposal(state),{storage}),/操作記録/);storage.values.set(STATE_KEY,'{bad');assert.throws(()=>loadIncomeState(storage));assert.equal(storage.values.get('retirement-sim-config-v0.9'),'old');});
test('operation time is validated before saving',async()=>{const {state,storage}=setup(),writes=storage.writes;await assert.rejects(applyIncomePreview(state,proposal(state),{storage,now:'bad'}),/操作日時/);assert.equal(storage.writes,writes);});
