import test from 'node:test';
import assert from 'node:assert/strict';
import {migrateConfig} from './storage.mjs';
import {runRetirementPlan} from './calc.mjs';
import {listIncomeReferences,createIncomeDraft,previewIncomeAdoption,revalidateIncomePreview} from './income-preview.mjs';

function setup(){
 const c=migrateConfig({people:{primary:{birthDate:'1980-08-27'},spouse:{birthDate:'1981-05-01'}},plan:{startAge:64,endAge:67,startDate:'2044-08-27',initialAsset:1000,initialAssetIncludesIdeco:false,afterTaxReturn:0,inflation:0},employment:{primary:{mainRetirement:{baseDate:'2045-08-27'},sideWork:{monthlyGross:0}},spouse:{sideWork:{monthlyGross:0}}},income:{pensions:{primary:{annualAtStart:0},spouse:{annualAtStart:0}}},budgets:[{fromAge:65,toAge:90,annualBudget:0}],unemployment:{baselineMode:'none'},events:[]});
 c.cashflow.manualIncomeItems=[{key:'gift',label:'贈与',unit:'annual',periods:[{fromAge:65,toAge:65,amount:120,note:'keep'}]}];
 const state={config:c,scenarios:[{id:'a',name:'比較A',role:'scenario',selected:true,config:structuredClone(c)},{id:'b',name:'比較B',role:'reference',config:structuredClone(c)}],future:{keep:[1]}};
 return state;
}
function draft(state,{amount=120,treatment='separate'}={}){const r=listIncomeReferences(state)[0],d=createIncomeDraft(state);d.selection={itemId:r.itemId,ruleRef:r.ruleRef,period:r.period,unit:r.unit,priceBasis:r.priceBasis,amount,fundingTreatment:treatment};return d;}

test('reference income is read only and never enters assets before adoption',()=>{const s=setup(),before=structuredClone(s),r=runRetirementPlan(s.config);assert.equal(r.rows.find(x=>x.age===65).extraIncome,0);assert.equal(listIncomeReferences(s).length,1);assert.deepEqual(s,before);});
test('preview creates one traced posted row and changes only extra income',()=>{const s=setup(),p=previewIncomeAdoption(s,draft(s));assert.equal(p.changed,true);assert.equal(p.candidate.config.cashflow.periodOverrides.length,1);const row=p.candidate.config.cashflow.periodOverrides[0];assert.equal(row.source,'income-adoption-v1');assert.equal(row.amount,120);assert.equal(row.fundingTreatment,'separate');assert.equal(p.annualDeltas[0].delta,120);assert.equal(p.finalAssetAfter-p.finalAssetBefore,120);assert.deepEqual(p.candidate.scenarios,s.scenarios);assert.deepEqual(p.candidate.future,s.future);});
test('monthly reference keeps its unit and posts twelve monthly amounts',()=>{const s=setup();s.config.cashflow.manualIncomeItems[0].unit='monthly';s.config.cashflow.manualIncomeItems[0].periods[0].amount=2;const p=previewIncomeAdoption(s,draft(s,{amount:3}));assert.equal(p.reference.unit,'monthly');assert.equal(p.months.length,12);assert.equal(p.annualDeltas[0].delta,36);});
test('same adoption is updated instead of appended',()=>{const s=setup(),first=previewIncomeAdoption(s,draft(s));const next=first.candidate,p=previewIncomeAdoption(next,draft(next,{amount:180}));assert.equal(p.candidate.config.cashflow.periodOverrides.length,1);assert.equal(p.beforeRow.amount,120);assert.equal(p.afterRow.amount,180);assert.equal(p.annualDeltas[0].delta,60);});
test('same adopted value is a no-change preview',()=>{const s=setup(),first=previewIncomeAdoption(s,draft(s)),p=previewIncomeAdoption(first.candidate,draft(first.candidate));assert.equal(p.changed,false);assert.equal(p.candidate.config.cashflow.periodOverrides.length,1);});
test('unrelated income in same period is retained and not treated as the reference',()=>{const s=setup();s.config.cashflow.periodOverrides=[{kind:'income',key:'rent-income',label:'家賃収入',fromAge:65,toAge:65,amount:12,unit:'annual',fundingTreatment:'separate',future:{keep:1}}];const p=previewIncomeAdoption(s,draft(s));assert.equal(p.candidate.config.cashflow.periodOverrides.length,2);assert.deepEqual(p.candidate.config.cashflow.periodOverrides[0],s.config.cashflow.periodOverrides[0]);assert.equal(p.annualDeltas[0].delta,120);});
test('legacy row with the same source key blocks double posting',()=>{const s=setup();s.config.cashflow.periodOverrides=[{kind:'income',key:'gift',fromAge:65,toAge:65,amount:120,unit:'annual',fundingTreatment:'separate'}];assert.throws(()=>previewIncomeAdoption(s,draft(s)),/二重計上/);});
test('unsupported, ambiguous and forged references fail closed',()=>{for(const mode of ['unit','identity']){const s=setup();if(mode==='unit')s.config.cashflow.manualIncomeItems[0].unit='week';else delete s.config.cashflow.manualIncomeItems[0].key;assert.throws(()=>draft(s));}const s=setup(),d=draft(s);d.selection.ruleRef='forged';assert.throws(()=>previewIncomeAdoption(s,d));});
test('missing, string, negative and nonfinite amounts are not coerced',()=>{for(const amount of [undefined,'120',-1,NaN,Infinity]){const s=setup(),d=draft(s);d.selection.amount=amount;assert.throws(()=>previewIncomeAdoption(s,d),/金額/);}});
test('period, unit and price basis cannot be changed in the draft',()=>{for(const field of ['period','unit','priceBasis']){const s=setup(),d=draft(s);if(field==='period')d.selection.period={type:'age',fromAge:66,toAge:66};else d.selection[field]='changed';assert.throws(()=>previewIncomeAdoption(s,d),/期間・単位・価格基準/);}});
test('net transfer is unavailable until salary-life mode is explicitly adopted',()=>{const s=setup();assert.throws(()=>previewIncomeAdoption(s,draft(s,{treatment:'net_transfer'})),/給与生活方式/);});
test('salary-life net transfer is recorded without adding the same household money to assets',()=>{const s=setup();s.config.plan.endAge=64;s.config.cashflow.salaryLife={mode:'net-transfer-v1',lastSalaryMonth:'2045-07',monthlyAddition:0,monthlyWithdrawal:0};s.config.cashflow.manualIncomeItems[0].periods[0]={fromAge:64,toAge:64,amount:12};const p=previewIncomeAdoption(s,draft(s,{amount:12,treatment:'net_transfer'}));assert.equal(p.changed,true);assert.equal(p.finalAssetAfter,p.finalAssetBefore);assert.equal(p.months.length,0);assert.equal(p.afterRow.fundingTreatment,'net_transfer');});
test('stale draft and tampered preview require recalculation',()=>{const s=setup(),d=draft(s),p=previewIncomeAdoption(s,d);s.scenarios[0].selected=false;assert.throws(()=>previewIncomeAdoption(s,d),/変わりました/);const original=setup(),clean=previewIncomeAdoption(original,draft(original));clean.candidate.config.plan.initialAsset=999;assert.throws(()=>revalidateIncomePreview(original,clean),/再試算/);});
test('preview does not access storage, DOM, clock or mutate inputs',()=>{const s=setup(),before=structuredClone(s);for(const name of ['localStorage','document'])Object.defineProperty(globalThis,name,{configurable:true,get(){throw new Error(name);}});try{previewIncomeAdoption(s,draft(s));}finally{delete globalThis.localStorage;delete globalThis.document;}assert.deepEqual(s,before);});
