import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {mountIncomeSheet,assertIncomeScreenMatches} from './income-ui.mjs';
import {migrateConfig,STATE_KEY} from './storage.mjs';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
class Element{value='';checked=false;disabled=false;hidden=false;textContent='';children=[];listeners={};addEventListener(type,fn){this.listeners[type]=fn;}append(e){this.children.push(e);}replaceChildren(){this.children=[];this.value='';}async emit(type){if(type==='click'&&this.disabled)return;return this.listeners[type]?.();}}
function setup({brokenCommit=false}={}){
 const nodes=new Map([...html.matchAll(/\bid="(income[^"]+)"/g)].map(x=>[x[1],new Element()]));const doc={getElementById:id=>nodes.get(id),createElement:()=>new Element()};const node=id=>doc.getElementById('income'+id);node('Treatment').value='separate';
 const c=migrateConfig({people:{primary:{birthDate:'1980-08-27'},spouse:{birthDate:'1981-05-01'}},plan:{startAge:64,endAge:67,startDate:'2044-08-27',initialAsset:1000,initialAssetIncludesIdeco:false,afterTaxReturn:0,inflation:0},employment:{primary:{mainRetirement:{baseDate:'2045-08-27'},sideWork:{monthlyGross:0}},spouse:{sideWork:{monthlyGross:0}}},income:{pensions:{primary:{annualAtStart:0},spouse:{annualAtStart:0}}},budgets:[{fromAge:65,toAge:90,annualBudget:0}],unemployment:{baselineMode:'none'},events:[]});c.cashflow.manualIncomeItems=[{key:'gift',label:'贈与',unit:'annual',periods:[{fromAge:65,toAge:65,amount:120}]}];
 let state={config:c,scenarios:[{id:'a',name:'A',role:'scenario',selected:true,config:structuredClone(c)},{id:'b',name:'B',role:'reference',config:structuredClone(c)}],future:{keep:1}},display={config:migrateConfig(c),scenarios:state.scenarios.map(x=>({...x,config:migrateConfig(x.config)}))};
 const storage={raw:JSON.stringify(state),fail:false,writes:0,getItem(k){assert.equal(k,STATE_KEY);return this.raw;},setItem(k,v){assert.equal(k,STATE_KEY);if(this.fail)throw new Error('QuotaExceeded');this.writes++;this.raw=v;}};const notices=[];
 const api=mountIncomeSheet({doc,storage,getState:()=>display,onCommit:n=>{if(brokenCommit)throw new Error('render');state=n.state;display={config:migrateConfig(state.config),scenarios:state.scenarios.map(x=>({...x,config:migrateConfig(x.config)}))};api.render();},showNotice:s=>notices.push(s)});api.render();
 async function trial(amount='120'){node('Amount').value=amount;await node('Amount').emit('input');await node('Trial').emit('click');}async function confirm(){node('Reviewed').checked=true;await node('Reviewed').emit('change');}
 return {node,api,storage,trial,confirm,get:()=>JSON.parse(storage.raw),display:()=>display,setDisplay:x=>display=x,notices};
}
test('opening and selecting reference never writes or enables apply',()=>{const t=setup();assert.equal(t.storage.writes,0);assert.equal(t.node('Rule').children.length,1);assert.equal(t.node('Apply').disabled,true);assert.match(t.node('Adopted').textContent,/内部ID/);});
test('input preview review apply reload and undo are explicit',async()=>{const t=setup(),before=t.get();await t.trial('180');assert.equal(t.storage.writes,0);assert.equal(t.node('Preview').hidden,false);assert.equal(t.node('Apply').disabled,true);assert.match(t.node('PreviewBody').textContent,/給与・年金・雇用保険・iDeCo受取/);await t.confirm();await t.node('Apply').emit('click');assert.equal(t.get().config.cashflow.periodOverrides.length,1);assert.deepEqual(t.get().scenarios,before.scenarios);assert.deepEqual(t.get().future,before.future);assert.match(t.node('History').textContent,/日本時間/);await t.node('Undo').emit('click');assert.equal(t.get().config.cashflow.periodOverrides.length,0);});
test('failed save retains input preview and adopted state then retry succeeds',async()=>{const t=setup();await t.trial();await t.confirm();const before=t.storage.raw;t.storage.fail=true;await t.node('Apply').emit('click');assert.equal(t.storage.raw,before);assert.equal(t.node('Amount').value,'120');assert.equal(t.node('Preview').hidden,false);assert.match(t.node('Error').textContent,/入力は保持/);t.storage.fail=false;await t.node('Apply').emit('click');assert.equal(t.get().config.cashflow.periodOverrides.length,1);});
test('double click commits once and creates one posted row',async()=>{const t=setup();await t.trial();await t.confirm();await Promise.all([t.node('Apply').emit('click'),t.node('Apply').emit('click')]);assert.equal(t.storage.writes,1);assert.equal(t.get().config.cashflow.periodOverrides.length,1);assert.equal(t.get().config.incomeWorkflow.history.length,1);});
test('editing amount or treatment invalidates preview and confirmation',async()=>{for(const field of ['Amount','Treatment']){const t=setup();await t.trial();await t.confirm();if(field==='Amount'){t.node(field).value='130';await t.node(field).emit('input');}else{t.node(field).value='net_transfer';await t.node(field).emit('change');}assert.equal(t.node('Preview').hidden,true);assert.equal(t.node('Reviewed').checked,false);assert.equal(t.node('Apply').disabled,true);}});
test('invalid values never write or enable apply',async()=>{for(const value of ['','-1','Infinity','abc']){const t=setup();await t.trial(value);assert.equal(t.storage.writes,0);assert.equal(t.node('Apply').disabled,true);assert.match(t.node('Error').textContent,/0以上/);}});
test('external update keeps draft and blocks all write actions',async()=>{const t=setup();await t.trial('180');t.api.invalidate();assert.equal(t.node('Amount').value,'180');assert.equal(t.node('Trial').disabled,true);assert.equal(t.node('Apply').disabled,true);assert.equal(t.node('Undo').disabled,true);});
test('screen match includes scenario selection and top-level values',()=>{const t=setup(),d=structuredClone(t.display());d.scenarios[0].selected=false;assert.throws(()=>assertIncomeScreenMatches(t.get(),d),/表示中/);});
test('post-save render failure is reported as saved and blocks work',async()=>{const t=setup({brokenCommit:true});await t.trial();await t.confirm();await t.node('Apply').emit('click');assert.equal(t.storage.writes,1);assert.match(t.node('Error').textContent,/保存済み/);assert.equal(t.node('Apply').disabled,true);});
test('application wires income screen, disables legacy immediate income entry and caches dependencies',()=>{const app=fs.readFileSync(new URL('./app.mjs',import.meta.url),'utf8'),sw=fs.readFileSync(new URL('./sw.js',import.meta.url),'utf8');for(const s of ['incomeSheet.render()','incomeSheet.reset()','incomeSheet.invalidate()','mountIncomeSheet'])assert.ok(app.includes(s));for(const s of ['income-ui.mjs','income-workflow.mjs','income-preview.mjs'])assert.ok(sw.includes(s));assert.ok(!html.includes('<option value="income">追加収入</option>'));assert.match(app,/追加収入は専用画面/);assert.match(app,/専用画面で管理/);});
